services:
  db:
    image: postgres:15
    container_name: postgresss
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 132435
      POSTGRES_DB: ulula
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: fastapiii
    command: >
      bash -c "
        uvicorn main:app --host 0.0.0.0 --port 8000
      "
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: