"""user_id in Shared_link

Revision ID: 6a73f08e72d4
Revises: b1d5ee5d2d73
Create Date: 2025-05-20 11:13:19.406248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a73f08e72d4'
down_revision: Union[str, None] = 'b1d5ee5d2d73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_links', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'shared_links', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shared_links', type_='foreignkey')
    op.drop_column('shared_links', 'user_id')
    # ### end Alembic commands ###
