"""feat: update teacher

Revision ID: 754efd2912a5
Revises: 506e77922264
Create Date: 2025-05-19 22:15:37.744548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '754efd2912a5'
down_revision: Union[str, None] = '506e77922264'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.add_column('teachers', sa.Column('telegram', sa.String(length=255), nullable=True))
    op.add_column('teachers', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'avatar_url')
    op.drop_column('teachers', 'telegram')
    op.drop_column('teachers', 'nickname')
    # ### end Alembic commands ###
