"""add subject in group_files

Revision ID: 191a7cbc3779
Revises: e20bda1ac0d1
Create Date: 2025-05-15 16:58:53.619867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '191a7cbc3779'
down_revision: Union[str, None] = 'e20bda1ac0d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_files', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'group_files', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_files', type_='foreignkey')
    op.drop_column('group_files', 'subject_id')
    # ### end Alembic commands ###
