"""Make level not null

Revision ID: 216a9b9ebdfb
Revises: f92103c995ed
Create Date: 2025-06-10 05:47:08.265625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '216a9b9ebdfb'
down_revision: Union[str, None] = 'f92103c995ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'level',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('submissions', 'level',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
