"""Add picture to achieve

Revision ID: 2d169dfa37d9
Revises: 4131427d142e
Create Date: 2025-06-10 03:27:39.114841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d169dfa37d9'
down_revision: Union[str, None] = '4131427d142e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('image_path', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'image_path')
    # ### end Alembic commands ###
