"""Add unique

Revision ID: 345d87ccc3ca
Revises: 1ebb0949a5b3
Create Date: 2025-05-11 15:46:26.096325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345d87ccc3ca'
down_revision: Union[str, None] = '1ebb0949a5b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'subjects', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='unique')
    # ### end Alembic commands ###
