"""Teacher_schedule

Revision ID: 3947759136c3
Revises: c1ca37fbbc5a
Create Date: 2025-05-12 20:11:43.581080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3947759136c3'
down_revision: Union[str, None] = 'c1ca37fbbc5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('teacher_schedule_teacher_id_fkey', 'teacher_schedule', type_='foreignkey')
    op.create_foreign_key(None, 'teacher_schedule', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_schedule', type_='foreignkey')
    op.create_foreign_key('teacher_schedule_teacher_id_fkey', 'teacher_schedule', 'groups', ['teacher_id'], ['group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###
