"""Maxim migrations(achivments and students)

Revision ID: 84c3d528bd3d
Revises: 6085eb4fbbcb
Create Date: 2025-05-15 19:27:19.878641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c3d528bd3d'
down_revision: Union[str, None] = '6085eb4fbbcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_achievements',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'achievement_id')
    )
    op.add_column('students', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('students', sa.Column('nickname', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('telegram', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'avatar_url')
    op.drop_column('students', 'telegram')
    op.drop_column('students', 'nickname')
    op.drop_column('students', 'full_name')
    op.drop_table('student_achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
