"""False init

Revision ID: 882115df2426
Revises: 
Create Date: 2025-06-09 17:09:02.022883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882115df2426'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_number', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('group_number')
    )
    op.drop_table('assignments')
    op.drop_table('submissions')
    op.drop_table('lab_works')
    op.create_foreign_key(None, 'group_files', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_subjects', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'schedule', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'group_subjects', type_='foreignkey')
    op.drop_constraint(None, 'group_files', type_='foreignkey')
    op.create_table('lab_works',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('lab_works_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.id'], name='lab_works_created_by_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['file_id'], ['group_files.id'], name='lab_works_file_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name='lab_works_subject_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='lab_works_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('assignment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mark', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], name='submissions_assignment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='submissions_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='submissions_pkey')
    )
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lab_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('deadline_at', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['lab_works.id'], name='assignments_lab_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], name='assignments_teacher_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='assignments_pkey')
    )
    op.drop_table('groups')
    # ### end Alembic commands ###
