"""Group update migrations

Revision ID: 8fffbc0289a1
Revises: 84c3d528bd3d
Create Date: 2025-05-15 19:37:18.144864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fffbc0289a1'
down_revision: Union[str, None] = '84c3d528bd3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'groups', ['group_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    # ### end Alembic commands ###
