"""Add labs

Revision ID: 9b4c9378d03a
Revises: 6a73f08e72d4
Create Date: 2025-06-09 17:17:30.131856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4c9378d03a'
down_revision: Union[str, None] = '6a73f08e72d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'assignments', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_files', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'group_subjects', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'groups', ['group_number'])
    op.create_foreign_key(None, 'schedule', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['group_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'schedule', type_='foreignkey')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'group_subjects', type_='foreignkey')
    op.drop_constraint(None, 'group_files', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    # ### end Alembic commands ###
