"""Add avatar in student

Revision ID: a6e353551f84
Revises: 96ca24231675
Create Date: 2025-05-11 19:41:53.648175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6e353551f84'
down_revision: Union[str, None] = '96ca24231675'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('avatar_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'avatar_url')
    # ### end Alembic commands ###
