"""Teacher_schedule

Revision ID: c1ca37fbbc5a
Revises: 3cf872b948a8
Create Date: 2025-05-12 20:10:35.034114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ca37fbbc5a'
down_revision: Union[str, None] = '3cf872b948a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_schedule',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('monday', sa.JSON(), nullable=True),
    sa.Column('tuesday', sa.JSON(), nullable=True),
    sa.Column('wednesday', sa.JSON(), nullable=True),
    sa.Column('thursday', sa.JSON(), nullable=True),
    sa.Column('friday', sa.JSON(), nullable=True),
    sa.Column('saturday', sa.JSON(), nullable=True),
    sa.Column('sunday', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['groups.group_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'week_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_schedule')
    # ### end Alembic commands ###
